# -*- coding: utf-8 -*-
"""regression problem (basic code).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4XEBWndQhOAQesoYGKpryoxFMjVVPoo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("canada house pricesing.csv",names=['a','area','price'])

df.head()

new_df = df.drop(['a'],axis = 1)

new_df

plt.scatter(df.area,df.price,color = "red",marker= "+")
plt.xlabel("area")
plt.ylabel("price")
plt.title("canada house price")
plt.show()

X = new_df.drop(['price'],axis=1)

X.head()

X.isnull().sum()

X = X.dropna()

X.head()

Y = df[['price']].dropna()

Y.head()

Y.isnull().sum()

model = linear_model.LinearRegression()
line = model.fit(X,Y)

line.predict([[1971]])

line.predict([[2021]])



